# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal


## Steps:
# actions/checkout@v4: Checks out your repository code so that the workflow can access it.
# actions/setup-dotnet@v4: Sets up the .NET SDK specified by dotnet-version.
# dotnet restore: Restores dependencies as specified in the project files.
# dotnet build --no-restore: Builds the project, skipping the restore step since it's already handled.
# dotnet test --no-build --verbosity normal: Runs tests without rebuilding the project, and sets the verbosity to normal for detailed test output.
